name 'cesnet-oozie'
version '0.9.1'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-oozie'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Setup Apache Oozie Workflow Scheduler'
description 'Setup Apache Oozie Workflow Scheduler'
project_page 'https://github.com/MetaCenterCloudPuppet'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
dependency 'adrien/alternatives', '>= 0.3.0 <1.0.0'
dependency 'cesnet/hadoop', '>= 0.9.4 <3.0.0'
